# -*- coding: utf-8 -*-
"""Aula3-Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZARsO_vS51ELav8-MImDN5Q9V1ILm0k
"""

SNAKE CASE
EXPLICAÇÃO
ctrl+: =comenta tudo o que estiver selecionado
ctrl+a = descomenta
ctrl+enter = executa o codigo
Selecionar todas as palavras iguais = ctrl+d
nome_de_usuario=input("Digite seu nome: ")
print(nome_de_usuario)
concatenar (,) =juntar uma variavel com um numero

numero1 = 'q'
numero2 = 20
print (numero1 , numero2)


pedir para o usuário digitar o nome , a idade e a cidade e depois concatenar tudo

name = input('digite seu nome: ')
age = input('digite sua idade: ')
ciage input('digite sua agede: ')

print('ageme do usuário é ',name, ', sua idade é,',age,'anos',' e ele mora na cidade:',city)

Crie um sistema que peça ao usuário o estado civil
Em seguida contatene com a seguinte frase - 'O usuário é'

estado_civil=input('Digite seu estado civil: ')
print('O usuário é ',estado_civil)
estado_civil=input('Digite seu estado civil: ')
text = 'O usuário é '
print(text,estado_civil)


DADOS PRIMITIVOS
dinheiro_real=1.25  #REAIS
boleano=True or False #BOLEANOS
char= 'Text'#STRINGS  OU CARACTERES
inteiro= 2 # INTEIROS
print(dinheiro_real,boleano,char,inteiro)


constantes
EM PYTHON SÃO CONVENÇÕES

CPF = 10
print(CPF)

EXERCICIOS

1 CRIE UM SISTEMA QUE SOME 2  NUMEROS ***

FORMA COM INPUT
numero1=int(input ('Digite o primeiro numero: '))
numero2=int(input ('Digite o segundo numero: '))
soma=numero1+numero2
print('A soma dos dois numeros digitados é ',soma)

FORMA SEM INPUT
numero1=2
numero2=3
soma=numero1+numero2
print('A soma dos dois numeros digitados é ',soma) CERTO

2 CRIE UM SISTEMA QUE IMPRIMA SEU NOME NA TELA**
name=input('Digite seu nome: ')
print('Seu nome é:',name)

3 CRIE UM SISTEMA QUE IMPRIMA SEU NOME E UM CUMPRIMENTO APÓS nome(CONCATENE)
name=input('Digite seu nome: ')
print('O nome digitado foi :',name,'. Boa tarde Sr ',name)

**4 - CRIE UM SISTEMA QUE MULTIPLIQUE 2 NÚMEROS**
numero1=int(input ('Digite o primeiro numero: '))
numero2=int(input ('Digite o segundo numero: '))
multiplicacao=numero1*numero2
print('A multiplicação dos dois numeros digitados é ',multiplicacao)


SINAIS DE COMPARAÇÃO
COMPARAR OS DADOS
COMPARA TODOS OS DADOS PRIMITIVOS

=  ATRIBUIÇÃO
== IGUALDADE
*  MULTIPLICAÇÃO
+  SOMA
-  SUBTRAÇÃO

>   MAIOR
<   MENOR
<=  MENOR OU IGUAL
>=  MAIOR OU IGUAL
!=  DIFERENTE


CONDICIONAIS (SE) E SINAIS DE COMPARAÇÃO

Declare uma variável de número inteiro e verifique se ele é maior que 10

n1=10
if n1 <= 100 :
   print ('A variável é menor que 100')

CONDICIONAL COMPOSTA

senha_correta = '123456'
senha_digitada = input('Digite uma senha')

if senha_digitada == senha_correta:
   print('Acesso autorizado')
else:
      print('Acesso negado')


print('Acesso ao show')
idade = int(input('Digite sua idade'))
if idade <= 17:
    print('Acesso negado')
else:
   print('Acesso confirmado')

print('Acesso ao show')  ERRO
idade = input('Digite sua idade')
if idade <= "17":
    print('Acesso negado')
else:
   print('Acesso confirmado')


INDENTAÇÃO = ORGANIZAÇÃO DO CÓDIGO
rua = 'rua 10'
if rua != 'rua 10':
  print('Não é na rua 10')
else:
  print('A festa é na rua 10')

print('Vacinas para pessoas com 18 anos')
idade = 18
if idade != 18:
  print('Não precisa tomar a vacina')
else:
  print('Precisa se vacinar')

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
if n2 > n1:
  print('O segundo número foi o',n2,'ele é maior que o primeiro número digitado')
else:
  print('O primeiro número foi o ',n1,' e ele é maior que o segundo número digitado')

EXERCICIO 2

## 1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

numero =int(input('Digite um número para que seja elevado ao quadrado:'))
quadrado= numero**2
print('O número digitado foi ',numero,' que elevado ao quadrado resultou em ',quadrado)


## 2 -Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.
name=input('Digite seu nome ')
middle_name=input('Digite o seu nome do meio ')
last_name=input('Digite seu último nome ')
print('O seu nome completo é ', name,middle_name,last_name)

## 3 -Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.

number1=input('Digite um número')
number2=input('DIgite o segundo número')
print(number1,number2)

## 4 -Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.
palavra='Python'
numero=2
print(palavra,numero)

EXERCICIOS IF

**1 - Crie uma condição para comparar idades: 45 e 18 -  QUAL É MENOR E QUAL É MAIOR?**

age1 = 45
age2 = 18

if age1 > age2:
    print('A primeira idade é :',age1,'ela é maior que a segunda idade : ',age2)


**2 - Crie um sistema para permitir a verificação de menores em um show**

print('Acesso ao show apenas para maiores')
idade = int(input('Digite sua idade:'))
if idade <= 17:
     print('Acesso negado')
else:
    print('Acesso confirmado')

**3 - Crie um algoritmo que permita a entrada de 3 notas de alunos, utilize o bloco de código if()**

**para verificar se o aluno passou.**

print('Calculo de média')
print('O aluno será aprovado apenas se a nota for maior ou igual a 7')

nota_aluno_1= int(input('Digite a nota do primeiro aluno:\n'))
nota_aluno_2= int(input('Digite a nota do segundo aluno:\n'))
nota_aluno_3= int(input('Digite a nota do terceiro aluno:\n'))

print('\n Anota do primeiro aluno foi ',nota_aluno_1,'.')
if nota_aluno_1 >=7:
   print('O primeiro aluno foi aprovado\n')
else:
  print('O primeiro aluno foi reprovado\n')

print('Anota do segundo aluno foi ',nota_aluno_2,'.')
if nota_aluno_2 >=7:
   print('O segundo aluno foi aprovado\n')
else:
  print('O segundo aluno foi reprovado\n')

print('Anota do terceiro aluno foi ',nota_aluno_3,'.')
if nota_aluno_3 >=7:
   print('O terceiro aluno foi aprovado\n')
else:
  print('O terceiro aluno foi reprovado\n')


CALCULO DE MEDIA

print('Calculo de média')
print('O aluno será aprovado se a media for maior ou igual a 7')

nota1= int(input('Digite a primeira nota:'))
nota2= int(input('Digite a segunda nota:'))
nota3= int(input('Digite a terceira nota:'))
media = (nota1+nota2+nota3)/3
print('A sua media foi ',media)
if media >7:
   print('Parabéns, você foi aprovado !')
else:
  print('Reprovado.')

AULA 4

and not or


OR:

casa = 'grey'

if casa == 'green' or casa == 'blue':
    print('Bela casa')
else:
   print('pinte de roxo')

city= input('Digite sua cidade->')

if city == 'Guarulhos' or city=='São Paulo' or city=='Rio':
  print('Vou viajar')
else:
  print('Vou trabalhar')

AND:
age= int(input('Digite sua idade->'))
if age >= 18 and age <70:
    print('Vou me vacinar')
else:
    print('Não precisa vacinar')

VARIAVEL DE IMPRESSÃO
utilizando virgula
number=123
word='World'
print("Hello to the",word,number)

utilizando {}
number=123
word='World'
print("Hello to the {} {}".format (word,number))

utilizando o operador +
number=123
word='World'
print('Hello to the ' + word + str( number))

utilizando f- string
number=123
word='World'
print(f'Hello to the {word} {number}')



Exercício 1: Verificação de Número Positivo

Escreva um programa em Python que solicite ao
usuário um número inteiro e
verifique se o número é positivo, negativo ou zero.
Em seguida, exiba uma mensagem apropriada de acordo
com o resultado da verificação.

number=int(input('Digite um número inteiro: \n'))
if number >0:
  print('O número digitado foi o',number,'.Ele é um número positivo')
elif number == 0:
  print('O número digitado foi o 0')
else:
  print('O número digitado foi o',number,'.Ele é um número negativo')


Exercício 2: Classificação de Triângulos

Escreva um programa em Python que receba três comprimentos de lados de um triângulo e
determine se o triângulo
é equilátero, isósceles ou escaleno.
O triângulo equilátero é um tipo de triângulo que possui os três lados congruentes (mesma medida)
O Triângulo isósceles é um polígono que apresenta três lados, sendo DOIS deles congruentes (mesma medida).
O Triângulo escaleno é o polígono que possui três lados com diferentes

lado1=float(input('Digite o primeiro comprimento:\n'))
lado2=float(input('Digite o segundo comprimento:\n'))
lado3=float(input('Digite o terceiro comprimento:\n'))

print('\nAs medidas informadas foram:',lado1,',',lado2,'e',lado3)

if lado1 == lado2 == lado3:
  print('\nO triangulo formado pelas medidas informadas é um triângulo equilatero')
elif lado1 == lado2 != lado3 or lado1 == lado3 != lado2 or lado2 == lado3 != lado1 :
  print('\nO triangulo formado pelas medidas informadas é um triângulo isósceles')
else:
  print('\nO triangulo formado pelas medidas informadas é um triângulo escaleno')


Exercício 3: Verificação de Ano Bissexto UTILIZAÇÃO DE MODULO (%)

Um ano é bissexto se for divisível por 4, exceto para anos que são divisíveis por 100.
No entanto, anos divisíveis por 400
também são bissextos. Escreva um programa em Python que solicite um ano ao usuário
e determine se é um ano bissexto ou não.

ano  =  int(input("Digite o ano"))

if  ano % 4 == 0:
    print("O ano é bissexto")
else:
    print("Não é bissexto")

CONTINUAÇÃO EXERCICIOS AULA 03

**5 -
Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.**

frase='Meu nome é '
name=input('Digite o seu nome:\n')
print(frase,name)

**6 -**

**Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".**
horas=input('Digite a hora:\n')
minutos=input('Digite os minutos:\n')
segundos=input('Digite os segundos:\n')
print('Agora são ',horas,':',minutos,':',segundos)

**7 -
Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.**
ddd=input('Digite o DDD:\n')
telefone=input('Digite o número de telefone:\n')
print('O número de telefone é (',ddd,') 9',telefone)

**8 -
Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.**
ovos='ovos,'
leite='leite,'
farinha='farinha,'
manteiga='manteiga,'
acucar='açucar.'
print('Ingredientes :',ovos,leite,farinha,manteiga,acucar)

**9 -
Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.**
print('Digite três adjetivos que você possui para que seja criado uma frase.')
adjetivo1=input('Digite o primeiro adjetivo:\n')
adjetivo2=input('Digite o segundo adjetivo:\n')
adjetivo3=input('Digite o terceiro adjetivo:\n')
print('Você é uma pessoa única tendo em vista que possui as seguintes caracteristicas: ',adjetivo1,',',adjetivo2,',','e',adjetivo3,'!')


UTILIZANDO A FUNÇÃO "len"
UTILIZANDO A FUNÇÃO "len"
Serve apenas para medir o comprimento de uma string e não numeros
METODO E FUNÇÕES SÃO LIGADOS A AÇÃO

text='Olá mundo!'
comprimento = len(text)
print(comprimento)

TYPE

verdadeiro= True
tipo=type(verdadeiro)
print(tipo)

number= 100
tipo=type(number)
print(tipo)

int() float() str()

n1='10'
print(type(n1))
n2=15.0
print(type(n2))
n3=25
print(type(n3))
print('--------------\n')

v1 = int(n1)
print(type(v1))

v2 = str(n2)
print(type(v2))

v3 = float(n3)
print(type(v3))


-------------------------------------------------------------
LISTA (ARRAY)

palavra="Guarulhos"
lista= list(palavra)
print(lista)

for n in range(1,9):
print(n)

sum (SOMA)
lista = [2,3,6,8,9]
soma = sum(lista)
print(soma)

lista = [1,2,3,4,5]
soma = sum(lista)
print(soma)

max e min
exibe o primeiro ou ultimo caractere de uma seguência:
lista ='abcde'
l = max(lista)
print(l)


sorted = organiza os dados
n = [1,6,6,9,8454,454,1120,8,45]
organize = sorted(n)
print(organize)

AULA 05

text='Olá Mundo'
lista=list(text)
print(lista)

numeros=[1,3,6,89,12,78]
soma=sum(numeros)
print(soma)

Range
n=range(1,10)
print(n)

for n in range (1,10):
    print(n)

Loop For
Serve para evitar retrabalhos
Evita digitar muitas vezes um algoritmo

print('olá mundo')
print('olá mundo')
print('olá mundo')
print('olá mundo')
print('olá mundo')

"i" = Índice
print('------------\n')
for i in range(1,6):
   print('olá mundo',i)

frutas = ["maçã", "banana", "laranja"]
for fruta in frutas:
    print(fruta)

lista = [1,3,6,89,78,15,56]
for n in lista:
  print(n)

range


for n in range(1,20):
  print(n)

menino={
    'nome':'Carlos',
    'idade':17,
    'endereco':'rua 10'
}

for key,value  in menino.items():
  print(key,value)

matriz = [[1,2,3],[4,5,6],[7,8,9]]
for linha in matriz:
  for elemento in linha:
    print(elemento)

# EXERCÍCIOS:

**Exercício 1:** Escreva um programa que use a função `range()` para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

for i in range(2,22,2):
   print(i)

Exercício 2: Escreva um programa que use a função range() para gerar os múltiplos de 5 em 5 a 50 .


for i in range(5,51,5):
    print(i)

soma = sum(range(5,50,5))
print('A soma desta range é:',soma)

Exercício 3: Escreva um programa que use a função type() para verificar o tipo de uma variável.

dado='palavra'
tipo=type(dado)
print('O tipo da variável digitada é:',tipo)

Exercício 4: Escreva um programa que use a função print() para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.
name=input('Digite o seu nome:\n')
print('Seja bem vindo',name,'!')

Exercício 5: Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10.

for i in range(1,10,2):
    print(i)
soma = sum(range(1,10,2))
print('A soma desta range é:',soma)

